export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  NOT_FOUND: '*',
  STUDENT_DASHBOARD: '/dashboard',
  CAREER_PROFILE: '/profile',
  GOAL_SELECTION: '/goals',
  SKILL_INVENTORY: '/skills',
  GAP_ANALYSIS: '/gap-analysis',
  ROADMAP_BUILDER: '/roadmap',
  PROGRESS_TRACKING: '/progress',
  PROJECT_PLANNER: '/projects',
  MENTOR_REVIEW: '/mentor-review',
  NOTIFICATIONS: '/notifications',
  MENTOR_DASHBOARD: '/mentor/dashboard',
  STUDENT_DETAIL: '/mentor/student/:id',
  REVIEW: '/mentor/review',
  PLACEMENT_DASHBOARD: '/placement/dashboard',
  REPORTS: '/placement/reports',
  ADMIN_DASHBOARD: '/admin/dashboard',
  CAREER_ROLE_CATALOG: '/admin/career-roles',
  CONTENT_MANAGEMENT: '/admin/content-management',
  USER_MANAGEMENT: '/admin/user-management',
};
